services:
  - type: web
    name: api-users
    env: php
    plan: free
    region: oregon
    buildCommand: "composer install && php artisan migrate --force"
    startCommand: "php artisan serve --host 0.0.0.0 --port 8080"
    envVars:
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: ${RAILWAY_PRIVATE_DOMAIN} # Vem do Railway
      - key: DB_PORT
        value: 3306                     # Porta padrão do MySQL
      - key: DB_DATABASE
        value: ${MYSQL_DATABASE}        # Vem do Railway
      - key: DB_USERNAME
        value: ${MYSQLUSER}             # Vem do Railway
      - key: DB_PASSWORD
        value: ${MYSQL_ROOT_PASSWORD}   # Vem do Railway


